version: "3.4"
x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  mock-server:
    build: .
    image: mock-server:${MOCK_TAG}
    ports:
     - ${MOCK_METRICS_PORT}:${MOCK_METRICS_PORT}
    command: 
      - ./mock_python -p ${MOCK_METRICS_PORT} -s ${MOCK_SEMESTER}
#      - ./mock_python -p ${MOCK_METRICS_PORT} -s ${MOCK_SEMESTER} -l debug      
    restart: unless-stopped
    logging: *default-logging
